/* Main.ino file generated by New Project wizard
 *
 * Created:   周三 11月 2 2022
 * Processor: Arduino Nano
 * Compiler:  Arduino AVR (Proteus)
 */

const int button = 2;
const int Led = 13;
int GoState = 0;




void setup () {

// TODO: put your setup code here, to run once:
   pinMode(button,INPUT_PULLUP);
   pinMode(Led,OUTPUT);
}

void loop() {
   
   if(digitalRead(button)==LOW){
      while(digitalRead(button)==LOW){
	 GoState = !GoState;
      }
      if(GoState){
	 digitalWrite(Led,HIGH);
      }else{
	 digitalWrite(Led,LOW);
      }
    }
// TODO: put your main code here, to run repeatedly:
}
